title: Four Silver Strings
email: admin@foursilverstrings.com.au
description: >- # this means to ignore newlines until "baseurl:"
  Violinist since 1994
  Teaching since 2009
  Painting since 2011
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: four.silver.strings

# Build settings
# theme: minima
plugins:
  - jekyll-postcss
  - jekyll-feed

postcss:
  cache: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  paintings:
    output: true
    sort_by: order
    permalink: /:collection/:title

defaults:
  - scope:
      path: ""
      type: "paintings"
    values:
      layout: "painting"
